// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package roles

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
}
